"""Create Tournament table

Revision ID: 95ebac8275c8
Revises: 4d7c40233d4e
Create Date: 2024-02-08 13:19:07.670175

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "95ebac8275c8"
down_revision: Union[str, None] = "4d7c40233d4e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tournaments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("datetime", sa.DateTime(), nullable=False),
        sa.Column("sport_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["sport_id"], ["sports.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("tournaments")
    # ### end Alembic commands ###
