"""added name in Tournament table

Revision ID: 0b6473774550
Revises: 14931a74d135
Create Date: 2024-02-08 16:37:35.526515

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b6473774550'
down_revision: Union[str, None] = '14931a74d135'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tournaments', sa.Column('name', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'tournaments', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tournaments', type_='unique')
    op.drop_column('tournaments', 'name')
    # ### end Alembic commands ###
