"""Create athletes table

Revision ID: 4d7c40233d4e
Revises: 4523681363a0
Create Date: 2024-02-07 17:35:34.431264

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '4d7c40233d4e'
down_revision: Union[str, None] = '4523681363a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('athletes',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('first_name', sa.String(), nullable=False),
                    sa.Column('last_name', sa.String(), nullable=False),
                    sa.Column('age', sa.Integer(), nullable=False),
                    sa.Column('country', sa.String(), nullable=False),
                    sa.Column('sport_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['sport_id'], ['sports.id'],
                                            ondelete='SET NULL'),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('athletes')
    # ### end Alembic commands ###
